export const mockTransactions = [
    {
        comment: 'Cool food and wine!',
        date: '2021-07-01',
        expenses_category: 'Restaurants',
        expenses_subcategory: 'No fish',
        id: 1,
        income_category: null,
        income_subcategory: null,
        sum: -100000,
        wallet: 'Sber',
        wallet_from: null,
        wallet_to: null,
    },
    {
        comment: 'Video presentation',
        date: '2021-07-02',
        expenses_category: null,
        expenses_subcategory: null,
        id: 2,
        income_category: 'NLMK',
        income_subcategory: 'Video',
        sum: 200000,
        wallet: 'VTB',
        wallet_from: null,
        wallet_to: null,
    },
    {
        comment: 'From VTB to Sber',
        date: '2021-07-03',
        expenses_category: null,
        expenses_subcategory: null,
        id: 3,
        income_category: null,
        income_subcategory: null,
        sum: 50000,
        wallet: 'VTB',
        wallet_from: null,
        wallet_to: null,
    },
    {
        comment: 'Cool food and wine!',
        date: '2021-07-01',
        expenses_category: 'Restaurants',
        expenses_subcategory: 'No fish',
        id: Math.floor(Math.random() * 10000),
        income_category: null,
        income_subcategory: null,
        sum: -100000,
        wallet: 'Sber',
        wallet_from: null,
        wallet_to: null,
    },
];
